name: Release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'The release name to create'
        default: 'v1.0.0'
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm install
          npm run build:quill

      - name: Create Archive
        run: |
          mkdir -p release/quill
          cp -r ./packages/quill/dist ./release/quill
          npm pack ./release

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.name }}
          files: '*.tgz'
