name: Release

on:
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  release:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm install
          npm run build:quill

      - name: Create Archive
        run: |
          npm pack ./packages/quill/dist

      - uses: actions/upload-artifact@v4
        with:
          name: tar
          path: ./*.tgz
